github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addComment: false
    addBadge: false

tasks:
  - init: npm install && npm run build && npm run start